[tool.poetry]
name = "the-zen-of-python"
version = "0.1.0"
description = ""
authors = ["04sparing-lambert <04sparing-lambert@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
